"""
Prometheus + Grafana for the Lean Ethereum devnet.

Mirrors the docker-compose-metrics.yaml stack shipped in
blockblaz/lean-quickstart (prom v3.8.0, grafana v12.3.2, anonymous admin
login). Inside the Kurtosis enclave we scrape by service DNS name + port
instead of host.docker.internal:port, so no `--add-host` hackery is needed.

Layout:
  * One Prometheus service named "lean-prometheus" scraping every
    lean-<client>-<idx>:5054/metrics target plus its own /metrics.
  * One Grafana service named "lean-grafana" provisioning the Prometheus
    datasource and the upstream Lean client dashboard.

The whole thing is enabled by default when there are lean_participants;
add `additional_services: [grafana, prometheus]` to network_params.yaml
or set `lean_network_params.metrics_enabled: false` to skip it.
"""

constants = import_module("../../package_io/constants.star")

PROMETHEUS_IMAGE = "prom/prometheus:v3.8.0"
GRAFANA_IMAGE = "grafana/grafana:12.3.2"
PROMETHEUS_SERVICE = "lean-prometheus"
GRAFANA_SERVICE = "lean-grafana"
PROMETHEUS_PORT = 9090
GRAFANA_PORT = 3000

DASHBOARD_REL = "src/lean/metrics/grafana/dashboards/client-dashboard.json"


def launch(plan, lean_contexts):
    """Spin up Prometheus + Grafana for the given Lean nodes.

    Args:
        plan: Kurtosis plan.
        lean_contexts: list of `lean_context.new_lean_context` structs.
            Empty / None disables the stack.
    """
    if not lean_contexts:
        return None

    prometheus_artifact = _render_prometheus_config(plan, lean_contexts)
    grafana_provisioning = _render_grafana_provisioning(plan)
    grafana_dashboards = plan.upload_files(
        src="/" + DASHBOARD_REL,
        name="lean-grafana-dashboards",
    )

    # Pin host-side ports via public_ports so dashboards have stable URLs
    # across re-runs and so the operator can reach them via the host's
    # public hostname (e.g. http://my-host:3000) without an SSH tunnel.
    # Kurtosis's default `ports={}` publishes on a random host port bound
    # to 127.0.0.1; `public_ports={}` pins the host-side port and Docker
    # publishes it on 0.0.0.0 (the default `-p` behaviour).
    prometheus = plan.add_service(
        name=PROMETHEUS_SERVICE,
        config=ServiceConfig(
            image=PROMETHEUS_IMAGE,
            cmd=[
                "--config.file=/etc/prometheus/prometheus.yml",
                "--storage.tsdb.path=/prometheus",
                "--storage.tsdb.retention.time=30d",
                "--web.enable-lifecycle",
            ],
            ports={
                "http": PortSpec(
                    number=PROMETHEUS_PORT,
                    transport_protocol="TCP",
                    application_protocol="http",
                    wait=None,
                ),
            },
            public_ports={
                "http": PortSpec(
                    number=PROMETHEUS_PORT,
                    transport_protocol="TCP",
                    application_protocol="http",
                    wait=None,
                ),
            },
            files={"/etc/prometheus": prometheus_artifact},
        ),
    )

    grafana = plan.add_service(
        name=GRAFANA_SERVICE,
        config=ServiceConfig(
            image=GRAFANA_IMAGE,
            env_vars={
                "GF_SECURITY_ADMIN_USER": "admin",
                "GF_SECURITY_ADMIN_PASSWORD": "admin",
                "GF_USERS_ALLOW_SIGN_UP": "false",
                "GF_AUTH_ANONYMOUS_ENABLED": "true",
                "GF_AUTH_ANONYMOUS_ORG_ROLE": "Admin",
                "GF_AUTH_DISABLE_LOGIN_FORM": "true",
            },
            ports={
                "http": PortSpec(
                    number=GRAFANA_PORT,
                    transport_protocol="TCP",
                    application_protocol="http",
                    wait=None,
                ),
            },
            public_ports={
                "http": PortSpec(
                    number=GRAFANA_PORT,
                    transport_protocol="TCP",
                    application_protocol="http",
                    wait=None,
                ),
            },
            files={
                "/etc/grafana/provisioning": grafana_provisioning,
                "/var/lib/grafana/dashboards": grafana_dashboards,
            },
        ),
    )

    plan.print(
        "Lean metrics ready: prometheus={0}:{1}, grafana={2}:{3}".format(
            prometheus.ip_address,
            PROMETHEUS_PORT,
            grafana.ip_address,
            GRAFANA_PORT,
        )
    )
    return struct(
        prometheus=prometheus,
        grafana=grafana,
    )


def _render_prometheus_config(plan, lean_contexts):
    """Render prometheus.yml with one scrape target per Lean node."""
    template = """# Auto-generated by src/lean/metrics/metrics_launcher.star.
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "lean-devnet-metrics"

scrape_configs:
{{- range .Targets}}
  - job_name: "{{.Name}}"
    static_configs:
      - targets: ["{{.Target}}"]
        labels:
          client: "{{.Name}}"
          instance: "kurtosis"
{{end}}
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
"""
    targets = []
    for ctx in lean_contexts:
        targets.append(
            {
                "Name": ctx.service_name,
                # Kurtosis services resolve by service name within the
                # enclave network; ports are the internal port (not the
                # published host port). All Lean clients standardise on
                # 5054 for metrics.
                "Target": "{0}:{1}".format(ctx.service_name, ctx.metrics_port),
            }
        )
    return plan.render_templates(
        config={
            "prometheus.yml": struct(template=template, data={"Targets": targets}),
        },
        name="lean-prometheus-config",
        description="Rendering Lean prometheus.yml",
    )


def _render_grafana_provisioning(plan):
    """Render Grafana provisioning YAML files (datasource + dashboards)."""
    return plan.render_templates(
        config={
            "datasources/prometheus.yml": struct(
                template="""apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    uid: P1809F7CD0C75ACF3
    access: proxy
    url: http://{0}:{1}
    isDefault: true
    editable: true
""".format(
                    PROMETHEUS_SERVICE, PROMETHEUS_PORT
                ),
                data={},
            ),
            "dashboards/dashboards.yml": struct(
                template="""apiVersion: 1

providers:
  - name: "Lean Ethereum Dashboards"
    orgId: 1
    folder: ""
    type: file
    disableDeletion: false
    updateIntervalSeconds: 10
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards
      foldersFromFilesStructure: true
""",
                data={},
            ),
        },
        name="lean-grafana-provisioning",
        description="Rendering Lean Grafana provisioning",
    )
